### ISSUE TITLE
Error when running a simulation

### ISSUE THREAD

**Issue by meghana1310** [mortonne/cymr#5]
In [12]: from cymr import cmr

In [13]: model = cmr.CMRDistributed()

In [14]: sim = model.generate(data, param, param_def=param_def, patterns=patterns, n_rep=5)

Error Message:
KeyError                                  Traceback (most recent call last)
<ipython-input-34-15e0e57cf84a> in <module>()
----> 1 sim = model.generate(data, param, param_def=param_def, patterns=patterns, n_rep=5)

2 frames
/usr/local/lib/python3.6/dist-packages/cymr/cmr.py in prepare_list_param(n_item, n_sub, param, param_def)
    158             )
    159     else:
--> 160         Lcf_trial = primacy(n_item, param['Lcf'], param['P1'], param['P2'])
    161         Lcf = np.tile(Lcf_trial[:, None], (1, n_sub))
    162 

KeyError: 'P1'

**Comment by mortonne** [comment]
I'd recommend first updating cymr. I've changed the name of CMRDistributed, which is now CMR. The documentation has been updated accordingly. You can update the package using pip: `pip install git+https://github.com/mortonne/cymr`.

You haven't included the code that defines param, but from the error, it looks like the parameter 'P1' hasn't been defined. The [simulation tutorial](https://cymr.readthedocs.io/en/latest/guide/generation.html) has an example of how to set parameters by defining a dictionary with the values you want to set.
